### ISSUE TITLE
לא הצלחתי להבין

### ISSUE THREAD

**Issue by erelsgl** [flying-whales/flying-whales#33]
נכנסתי למבוא. ראיתי לווייתנים מעופפים, אבל לא הבנתי מה אני אמור לעשות - מה היעדים, מה התהליכים; איך אני זז ואיך אני מזיז את הלווייתנים, ואיפה אני בכלל על המסך?

גם, חלק מהטקסט נחתך אצלי - שימו לב לגודל ה-Player:
![image](https://github.com/flying-whales/flying-whales/assets/1462215/c4f3576b-19a5-4f8d-bb70-216a650e5b71)

**Comment by kggold4** [comment]
מוזר שזה נחתך ככה אצלך אולי זה בעיית רזולוציה?
הגדרנו את המשחק להיות 1920x1080 ובitch זה דווקא עובד טוב עם מסך מלא,
לגביי היעדים, המטרה של שלב הintro הוא ללמד את השחקן איך לשחק, איך לשלוט בליוויתנים ומה היעדים (למשל לשרוד, לאסוף נקודות, לתקוף וכו'...),
אנחנו מתכננים לקחת חצי מהtrailer שעשינו שמסביר על הבסיס ליעד המשחק ולשים אותו לפני שמתחילים את הintro

**Comment by kggold4** [comment]
@erelsgl 

ככה זה נראה כשאני עושה מסך בitch:
עובר main menu:

![image](https://github.com/flying-whales/flying-whales/assets/68167734/6794483b-b902-4fb3-8c16-72093def875a)

עבור השלב הראשון בintro:

![image](https://github.com/flying-whales/flying-whales/assets/68167734/d8ec21bb-e788-41cc-8ca7-c63cb40b7578)


מצד שמאל כתוב מה היעד הנוכחי ואיזה משימה זו מתוך כמה שיש בשלב הזה

**Comment by erelsgl** [comment]
העברתי למסך אחר, וזה נראה יותר טוב. הצלחתי לשחק במבוא. כללית, הוא בנוי טוב, עם משימות שמלמדות את השחקן בהדרגה איך לשחק. כמה הערות:

א. ההסברים למשימות לא ברורים. למשל, במשימה 1 צריך להסביר: "Click S to set the whales to Track mode. In this mode, the whales follow your cursor. Keep them in Track mode for at least 10 seconds to complete the task".

במשימה 2: "Click A to set the whales to Dynamic mode. In this mode, the whales wander around freely and gather food (points). Keep them in dynamic mode until they gather at least 20 points". 
(אגב, במקום נקודות, הייתי משנה את זה לאוכל - זה יותר מציאותי שלווייתנים אוספים אוכל).

אותו הדבר לגבי מצב התקפה.

ב. כדאי להוסיף את האות המתאימה ליד האייקון למטה (A, S, D) כדי שהשחקן יקשר ביניהם - לי לא היה ברור בהתחלה.

ג. המשימה של המטאורים מאד קלה - לא צריך לעשות כלום - רק לחכות (כי ממילא המטאור פוגע רק פגיעה חלשה שעוברת מהר).

ד. ה"מגן" מאד חזק - הוא הורס את כל המטאורים ואין לו שום עלות. למעשה אפשר להשתמש תמיד רק במגן. זו אסטרטגיה לא מאוזנת.

ה. משימה 7: לא הבנתי מה הכוונה "call for 2 whales" ואיך בדיוק עושים את זה?

ו. סיימתי את כל 9 המשימות, ולא קרה שום דבר - לא עברתי בחזרה לדף הראשי. רק ראיתי ניקוד שממשיך לגדול בלי סוף.

ז. לחצתי על Sky ועל Space ולא קרה שום דבר - האם השלבים האלה כבר בנויים?

**Comment by kggold4** [comment]
תודה רבה על הערות.
1. לגביי ההסבר המפורט על המשימה - אנחנו נטפל בזה שיהיה כותרת גדולה וטסקט קטן יותר מפורט כמו שאתה כתבת.
2. לגביי אייקונים עם כפתורים A,S,D, אנחנו נטפל בזה.
3. המשימה הקלה של המטאורים בעיקרון נועדה רק כדי ללמד את השחקן אבל נהפוך את זה ליותר מאתגר שלא ישעמם.
4. לגביי המגן - עידכנו כבר בגרסה הנוכחית (שלא נמצאת בitch) שהcooldown של המגן הוא יותר גדול - 10 שניות, אפשר גם להגדיל ליותר, בנוסף אנחנו נקצר עוד קצת את המגן שהשחקן יוכל פחות להשתמש בו ורק בערך פעם ב-15 שניות או יותר.
5. לגביי המשימה של `call for 2 whales`, לא שמנו לב, נטפל בזה.
6. לגביי זה שסיימת את כל המשימות - עשינו כבר מסך סיום של שלב שמימנו אפשר לעבור לשלב הבא, בגרסה ששיחקת אין את זה.
7. השלבים האלה בבנייה.

תודה רבה על הביקורת, לקחנו לצומת ליבנו :-)
