### ISSUE TITLE
התמונה של העכבר של השחקן 

### ISSUE THREAD

**Issue by VictoKu1** [flying-whales/flying-whales#38]
במקום התמונה הרגילה יש תמונה מוזרה מרובעת, יכול להיות שזה משהו בהגדרות קומפילציה של הפרויקט.

**Comment by VictoKu1** [comment]
הגודל של החלון של המשחק לא מתואם עם הדפדפן.

**Comment by VictoKu1** [comment]
שום דבר לא קורה במשחק כשלוחצים על Sky או Space.

**Comment by VictoKu1** [comment]
בשלב שצריך ליצר לויתן חדש אין הסבר שצריך ללחוץ על W.

**Comment by VictoKu1** [comment]
אחרי שמסימים את ההוראות לא ברור מה לעשות, הרמה של המשחק לא משתנה ואין אפשרות ללכת לתפריט הראשי.

**Comment by kggold4** [comment]
> במקום התמונה הרגילה יש תמונה מוזרה מרובעת, יכול להיות שזה משהו בהגדרות קומפילציה של הפרויקט.

אתה מתכוון לעכבר? זה יטופל :-)

**Comment by kggold4** [comment]
> 

עשינו שהמשחק יהיה 1920x1080 - כשמשחקים בitch צריך לעשות full screen לנו זה עובד מעולה

**Comment by kggold4** [comment]
> 

זה יטופל היום :-)

**Comment by kggold4** [comment]
> הגודל של החלון של המשחק לא מתואם עם הדפדפן.


עשינו שהמשחק יהיה 1920x1080 - כשמשחקים בitch צריך לעשות full screen לנו זה עובד מעולה

**Comment by kggold4** [comment]
> שום דבר לא קורה במשחק כשלוחצים על Sky או Space.

זה יטופל היום :-)

**Comment by kggold4** [comment]
> בשלב שצריך ליצר לויתן חדש אין הסבר שצריך ללחוץ על W.

זה תוקן, יעלה בגרסה הסופית

**Comment by kggold4** [comment]
> אחרי שמסימים את ההוראות לא ברור מה לעשות, הרמה של המשחק לא משתנה ואין אפשרות ללכת לתפריט הראשי.

זה תוקן, יעלה בגרסה הסופית
