### ISSUE TITLE
עדיין יש בעיה עם גודל המסך

### ISSUE THREAD

**Issue by erelsgl** [flying-whales/flying-whales#40]
המשחק שלכם כנראה מותאם לגודל מסך מסויים - בכל מסך בגודל אחר, הטקסט נחתך.

**Comment by erelsgl** [comment]
כך למשל זה נראה באחד המסכים שלי:

![image](https://github.com/flying-whales/flying-whales/assets/1462215/deceef4e-e7b6-45a7-a484-f5542040f8eb)

**Comment by kggold4** [comment]
@erelsgl 

נשמח שתבדוק עכשיו אם תוקנה הבעיה
